export const roles: any =[ 
    { 
       "itemName":"d.risk",
       "parentPermissionId":null,
       "permissionId":2674,
       "permissionToChild":2674
    },
    { 
       "itemName":"g.enrich",
       "parentPermissionId":2674,
       "permissionId":2598,
       "permissionToChild":2598
    },
    { 
       "itemName":"m.advancedSearch",
       "parentPermissionId":2598,
       "permissionId":2000,
       "permissionToChild":2000
    },
    { 
       "itemName":"m.onboarding",
       "parentPermissionId":2598,
       "permissionId":101,
       "permissionToChild":2912
    },
    { 
       "itemName":"g.discover",
       "parentPermissionId":2674,
       "permissionId":2553,
       "permissionToChild":2553
    },
    { 
       "itemName":"m.dashboard",
       "parentPermissionId":2553,
       "permissionId":111,
       "permissionToChild":3220
    },
    { 
       "itemName":"m.workspace",
       "parentPermissionId":2553,
       "permissionId":2913,
       "permissionToChild":2913
    },
    { 
       "itemName":"m.investigationConsole",
       "parentPermissionId":2553,
       "permissionId":2914,
       "permissionToChild":2914
    },
    { 
       "itemName":"m.transactionMonitoring",
       "parentPermissionId":2553,
       "permissionId":309,
       "permissionToChild":309
    },
    { 
       "itemName":"m.marketIntelligence",
       "parentPermissionId":2553,
       "permissionId":310,
       "permissionToChild":310
    },
    { 
       "itemName":"m.adverseTransactions",
       "parentPermissionId":2553,
       "permissionId":311,
       "permissionToChild":311
    },
    { 
       "itemName":"m.fraud",
       "parentPermissionId":2553,
       "permissionId":312,
       "permissionToChild":312
    },
    { 
       "itemName":"m.transactionIntelligence",
       "parentPermissionId":2553,
       "permissionId":313,
       "permissionToChild":313
    },
    { 
       "itemName":"m.eDiscovery",
       "parentPermissionId":2553,
       "permissionId":314,
       "permissionToChild":314
    },
    { 
       "itemName":"m.alertManagement",
       "parentPermissionId":2553,
       "permissionId":2486,
       "permissionToChild":2486
    },
    { 
       "itemName":"g.predict",
       "parentPermissionId":2674,
       "permissionId":2475,
       "permissionToChild":2475
    },
    { 
       "itemName":"Personalization",
       "parentPermissionId":2475,
       "permissionId":317,
       "permissionToChild":317
    },
    { 
       "itemName":"g.act",
       "parentPermissionId":2674,
       "permissionId":3362,
       "permissionToChild":3362
    },
    { 
       "itemName":"m.entity",
       "parentPermissionId":3362,
       "permissionId":318,
       "permissionToChild":318
    },
    { 
       "itemName":"m.cases",
       "parentPermissionId":3362,
       "permissionId":319,
       "permissionToChild":319
    },
    { 
       "itemName":"m.linkAnalysis",
       "parentPermissionId":3362,
       "permissionId":320,
       "permissionToChild":320
    },
    { 
       "itemName":"m.Underwriting",
       "parentPermissionId":3362,
       "permissionId":321,
       "permissionToChild":321
    },
    { 
       "itemName":"m.auditTrail",
       "parentPermissionId":3362,
       "permissionId":322,
       "permissionToChild":322
    },
    { 
       "itemName":"g.manage",
       "parentPermissionId":2674,
       "permissionId":3813,
       "permissionToChild":3813
    },
    { 
       "itemName":"m.systemSettings",
       "parentPermissionId":3813,
       "permissionId":3033,
       "permissionToChild":3033
    },
    { 
       "itemName":"m.Orchestration",
       "parentPermissionId":3813,
       "permissionId":323,
       "permissionToChild":323
    },
    { 
       "itemName":"m.appManager",
       "parentPermissionId":3813,
       "permissionId":324,
       "permissionToChild":324
    },
    { 
       "itemName":"m.dataManagement",
       "parentPermissionId":3813,
       "permissionId":325,
       "permissionToChild":325
    },
    { 
       "itemName":"m.systemMonitoring",
       "parentPermissionId":3813,
       "permissionId":326,
       "permissionToChild":326
    },
    { 
       "itemName":"m.bigDataSciencePlatform",
       "parentPermissionId":3813,
       "permissionId":327,
       "permissionToChild":327
    },
    { 
       "itemName":"m.policyEnforcement",
       "parentPermissionId":3813,
       "permissionId":328,
       "permissionToChild":328
    },
    { 
       "itemName":"m.questionnaireBuilder",
       "parentPermissionId":3813,
       "permissionId":329,
       "permissionToChild":329
    },
    { 
       "itemName":"m.dataCuration",
       "parentPermissionId":3813,
       "permissionId":330,
       "permissionToChild":330
    },
    { 
       "itemName":"m.decisioncoring",
       "parentPermissionId":3813,
       "permissionId":331,
       "permissionToChild":331
    },
    { 
       "itemName":"m.documentParsing",
       "parentPermissionId":3813,
       "permissionId":332,
       "permissionToChild":332
    },
    { 
       "itemName":"m.sourceManagement",
       "parentPermissionId":3813,
       "permissionId":1874,
       "permissionToChild":1874
    },
    { 
       "itemName":"m.userManagement",
       "parentPermissionId":3813,
       "permissionId":333,
       "permissionToChild":333
    },
    { 
       "itemName":"d.aml",
       "parentPermissionId":null,
       "permissionId":2677,
       "permissionToChild":2677
    },
    { 
       "itemName":"g.enrich",
       "parentPermissionId":2677,
       "permissionId":2599,
       "permissionToChild":2599
    },
    { 
       "itemName":"m.advancedSearch",
       "parentPermissionId":2599,
       "permissionId":2001,
       "permissionToChild":2000
    },
    { 
       "itemName":"m.onboarding",
       "parentPermissionId":2599,
       "permissionId":102,
       "permissionToChild":2912
    },
    { 
       "itemName":"g.discover",
       "parentPermissionId":2677,
       "permissionId":2597,
       "permissionToChild":2597
    },
    { 
       "itemName":"m.dashboard",
       "parentPermissionId":2597,
       "permissionId":112,
       "permissionToChild":3220
    },
    { 
       "itemName":"m.workspace",
       "parentPermissionId":2597,
       "permissionId":121,
       "permissionToChild":2913
    },
    { 
       "itemName":"m.investigationConsole",
       "parentPermissionId":2597,
       "permissionId":131,
       "permissionToChild":2914
    },
    { 
       "itemName":"m.transactionMonitoring",
       "parentPermissionId":2597,
       "permissionId":141,
       "permissionToChild":309
    },
    { 
       "itemName":"m.marketIntelligence",
       "parentPermissionId":2597,
       "permissionId":151,
       "permissionToChild":310
    },
    { 
       "itemName":"m.adverseTransactions",
       "parentPermissionId":2597,
       "permissionId":161,
       "permissionToChild":311
    },
    { 
       "itemName":"m.fraud",
       "parentPermissionId":2597,
       "permissionId":171,
       "permissionToChild":312
    },
    { 
       "itemName":"m.transactionIntelligence",
       "parentPermissionId":2597,
       "permissionId":181,
       "permissionToChild":313
    },
    { 
       "itemName":"m.eDiscovery",
       "parentPermissionId":2597,
       "permissionId":191,
       "permissionToChild":314
    },
    { 
       "itemName":"m.alertManagement",
       "parentPermissionId":2597,
       "permissionId":117,
       "permissionToChild":2486
    },
    { 
       "itemName":"g.predict",
       "parentPermissionId":2677,
       "permissionId":2470,
       "permissionToChild":2470
    },
    { 
       "itemName":"Personalization",
       "parentPermissionId":2470,
       "permissionId":601,
       "permissionToChild":317
    },
    { 
       "itemName":"g.act",
       "parentPermissionId":2677,
       "permissionId":3360,
       "permissionToChild":3360
    },
    { 
       "itemName":"m.entity",
       "parentPermissionId":3360,
       "permissionId":611,
       "permissionToChild":318
    },
    { 
       "itemName":"m.cases",
       "parentPermissionId":3360,
       "permissionId":621,
       "permissionToChild":319
    },
    { 
       "itemName":"m.linkAnalysis",
       "parentPermissionId":3360,
       "permissionId":631,
       "permissionToChild":320
    },
    { 
       "itemName":"m.Underwriting",
       "parentPermissionId":3360,
       "permissionId":641,
       "permissionToChild":321
    },
    { 
       "itemName":"m.auditTrail",
       "parentPermissionId":3360,
       "permissionId":651,
       "permissionToChild":322
    },
    { 
       "itemName":"g.manage",
       "parentPermissionId":2677,
       "permissionId":3815,
       "permissionToChild":3815
    },
    { 
       "itemName":"m.systemSettings",
       "parentPermissionId":3815,
       "permissionId":661,
       "permissionToChild":3033
    },
    { 
       "itemName":"m.Orchestration",
       "parentPermissionId":3815,
       "permissionId":671,
       "permissionToChild":323
    },
    { 
       "itemName":"m.appManager",
       "parentPermissionId":3815,
       "permissionId":681,
       "permissionToChild":324
    },
    { 
       "itemName":"m.dataManagement",
       "parentPermissionId":3815,
       "permissionId":691,
       "permissionToChild":325
    },
    { 
       "itemName":"m.systemMonitoring",
       "parentPermissionId":3815,
       "permissionId":711,
       "permissionToChild":326
    },
    { 
       "itemName":"m.bigDataSciencePlatform",
       "parentPermissionId":3815,
       "permissionId":721,
       "permissionToChild":327
    },
    { 
       "itemName":"m.policyEnforcement",
       "parentPermissionId":3815,
       "permissionId":731,
       "permissionToChild":328
    },
    { 
       "itemName":"m.questionnaireBuilder",
       "parentPermissionId":3815,
       "permissionId":741,
       "permissionToChild":329
    },
    { 
       "itemName":"m.dataCuration",
       "parentPermissionId":3815,
       "permissionId":751,
       "permissionToChild":330
    },
    { 
       "itemName":"m.decisioncoring",
       "parentPermissionId":3815,
       "permissionId":761,
       "permissionToChild":331
    },
    { 
       "itemName":"m.documentParsing",
       "parentPermissionId":3815,
       "permissionId":771,
       "permissionToChild":332
    },
    { 
       "itemName":"m.sourceManagement",
       "parentPermissionId":3815,
       "permissionId":781,
       "permissionToChild":1874
    },
    { 
       "itemName":"m.userManagement",
       "parentPermissionId":3815,
       "permissionId":791,
       "permissionToChild":333
    },
    { 
       "itemName":"d.marketIntelligence",
       "parentPermissionId":null,
       "permissionId":2354,
       "permissionToChild":2354
    },
    { 
       "itemName":"g.enrich",
       "parentPermissionId":2354,
       "permissionId":2573,
       "permissionToChild":2573
    },
    { 
       "itemName":"m.advancedSearch",
       "parentPermissionId":2573,
       "permissionId":2002,
       "permissionToChild":2000
    },
    { 
       "itemName":"m.onboarding",
       "parentPermissionId":2573,
       "permissionId":103,
       "permissionToChild":2912
    },
    { 
       "itemName":"g.discover",
       "parentPermissionId":2354,
       "permissionId":2797,
       "permissionToChild":2797
    },
    { 
       "itemName":"m.dashboard",
       "parentPermissionId":2797,
       "permissionId":113,
       "permissionToChild":3220
    },
    { 
       "itemName":"m.workspace",
       "parentPermissionId":2797,
       "permissionId":122,
       "permissionToChild":2913
    },
    { 
       "itemName":"m.investigationConsole",
       "parentPermissionId":2797,
       "permissionId":132,
       "permissionToChild":2914
    },
    { 
       "itemName":"m.transactionMonitoring",
       "parentPermissionId":2797,
       "permissionId":142,
       "permissionToChild":309
    },
    { 
       "itemName":"m.marketIntelligence",
       "parentPermissionId":2797,
       "permissionId":152,
       "permissionToChild":310
    },
    { 
       "itemName":"m.adverseTransactions",
       "parentPermissionId":2797,
       "permissionId":162,
       "permissionToChild":311
    },
    { 
       "itemName":"m.fraud",
       "parentPermissionId":2797,
       "permissionId":172,
       "permissionToChild":312
    },
    { 
       "itemName":"m.transactionIntelligence",
       "parentPermissionId":2797,
       "permissionId":182,
       "permissionToChild":313
    },
    { 
       "itemName":"m.eDiscovery",
       "parentPermissionId":2797,
       "permissionId":192,
       "permissionToChild":314
    },
    { 
       "itemName":"m.alertManagement",
       "parentPermissionId":2797,
       "permissionId":127,
       "permissionToChild":2486
    },
    { 
       "itemName":"g.predict",
       "parentPermissionId":2354,
       "permissionId":2440,
       "permissionToChild":2440
    },
    { 
       "itemName":"Personalization",
       "parentPermissionId":2440,
       "permissionId":602,
       "permissionToChild":317
    },
    { 
       "itemName":"g.act",
       "parentPermissionId":2354,
       "permissionId":3390,
       "permissionToChild":3390
    },
    { 
       "itemName":"m.entity",
       "parentPermissionId":3390,
       "permissionId":612,
       "permissionToChild":318
    },
    { 
       "itemName":"m.cases",
       "parentPermissionId":3390,
       "permissionId":622,
       "permissionToChild":319
    },
    { 
       "itemName":"m.linkAnalysis",
       "parentPermissionId":3390,
       "permissionId":632,
       "permissionToChild":320
    },
    { 
       "itemName":"m.Underwriting",
       "parentPermissionId":3390,
       "permissionId":642,
       "permissionToChild":321
    },
    { 
       "itemName":"m.auditTrail",
       "parentPermissionId":3390,
       "permissionId":652,
       "permissionToChild":322
    },
    { 
       "itemName":"g.manage",
       "parentPermissionId":2354,
       "permissionId":3819,
       "permissionToChild":3819
    },
    { 
       "itemName":"m.systemSettings",
       "parentPermissionId":3819,
       "permissionId":662,
       "permissionToChild":3033
    },
    { 
       "itemName":"m.Orchestration",
       "parentPermissionId":3819,
       "permissionId":672,
       "permissionToChild":323
    },
    { 
       "itemName":"m.appManager",
       "parentPermissionId":3819,
       "permissionId":682,
       "permissionToChild":324
    },
    { 
       "itemName":"m.dataManagement",
       "parentPermissionId":3819,
       "permissionId":692,
       "permissionToChild":325
    },
    { 
       "itemName":"m.systemMonitoring",
       "parentPermissionId":3819,
       "permissionId":712,
       "permissionToChild":326
    },
    { 
       "itemName":"m.bigDataSciencePlatform",
       "parentPermissionId":3819,
       "permissionId":722,
       "permissionToChild":327
    },
    { 
       "itemName":"m.policyEnforcement",
       "parentPermissionId":3819,
       "permissionId":732,
       "permissionToChild":328
    },
    { 
       "itemName":"m.questionnaireBuilder",
       "parentPermissionId":3819,
       "permissionId":742,
       "permissionToChild":329
    },
    { 
       "itemName":"m.dataCuration",
       "parentPermissionId":3819,
       "permissionId":752,
       "permissionToChild":330
    },
    { 
       "itemName":"m.decisioncoring",
       "parentPermissionId":3819,
       "permissionId":762,
       "permissionToChild":331
    },
    { 
       "itemName":"m.documentParsing",
       "parentPermissionId":3819,
       "permissionId":772,
       "permissionToChild":332
    },
    { 
       "itemName":"m.sourceManagement",
       "parentPermissionId":3819,
       "permissionId":782,
       "permissionToChild":1874
    },
    { 
       "itemName":"m.userManagement",
       "parentPermissionId":3819,
       "permissionId":792,
       "permissionToChild":333
    },
    { 
       "itemName":"d.financialCrime",
       "parentPermissionId":null,
       "permissionId":2232,
       "permissionToChild":2232
    },
    { 
       "itemName":"g.enrich",
       "parentPermissionId":2232,
       "permissionId":2652,
       "permissionToChild":2652
    },
    { 
       "itemName":"m.advancedSearch",
       "parentPermissionId":2652,
       "permissionId":2003,
       "permissionToChild":2000
    },
    { 
       "itemName":"m.onboarding",
       "parentPermissionId":2652,
       "permissionId":104,
       "permissionToChild":2912
    },
    { 
       "itemName":"g.discover",
       "parentPermissionId":2232,
       "permissionId":2707,
       "permissionToChild":2707
    },
    { 
       "itemName":"m.dashboard",
       "parentPermissionId":2707,
       "permissionId":114,
       "permissionToChild":3220
    },
    { 
       "itemName":"m.workspace",
       "parentPermissionId":2707,
       "permissionId":123,
       "permissionToChild":2913
    },
    { 
       "itemName":"m.investigationConsole",
       "parentPermissionId":2707,
       "permissionId":133,
       "permissionToChild":2914
    },
    { 
       "itemName":"m.transactionMonitoring",
       "parentPermissionId":2707,
       "permissionId":143,
       "permissionToChild":309
    },
    { 
       "itemName":"m.marketIntelligence",
       "parentPermissionId":2707,
       "permissionId":153,
       "permissionToChild":310
    },
    { 
       "itemName":"m.adverseTransactions",
       "parentPermissionId":2707,
       "permissionId":163,
       "permissionToChild":311
    },
    { 
       "itemName":"m.fraud",
       "parentPermissionId":2707,
       "permissionId":173,
       "permissionToChild":312
    },
    { 
       "itemName":"m.transactionIntelligence",
       "parentPermissionId":2707,
       "permissionId":183,
       "permissionToChild":313
    },
    { 
       "itemName":"m.eDiscovery",
       "parentPermissionId":2707,
       "permissionId":193,
       "permissionToChild":314
    },
    { 
       "itemName":"m.alertManagement",
       "parentPermissionId":2707,
       "permissionId":137,
       "permissionToChild":2486
    },
    { 
       "itemName":"g.predict",
       "parentPermissionId":2232,
       "permissionId":2430,
       "permissionToChild":2430
    },
    { 
       "itemName":"Personalization",
       "parentPermissionId":2430,
       "permissionId":603,
       "permissionToChild":317
    },
    { 
       "itemName":"g.act",
       "parentPermissionId":2232,
       "permissionId":3490,
       "permissionToChild":3490
    },
    { 
       "itemName":"m.entity",
       "parentPermissionId":3490,
       "permissionId":613,
       "permissionToChild":318
    },
    { 
       "itemName":"m.cases",
       "parentPermissionId":3490,
       "permissionId":623,
       "permissionToChild":319
    },
    { 
       "itemName":"m.linkAnalysis",
       "parentPermissionId":3490,
       "permissionId":633,
       "permissionToChild":320
    },
    { 
       "itemName":"m.Underwriting",
       "parentPermissionId":3490,
       "permissionId":643,
       "permissionToChild":321
    },
    { 
       "itemName":"m.auditTrail",
       "parentPermissionId":3490,
       "permissionId":653,
       "permissionToChild":322
    },
    { 
       "itemName":"g.manage",
       "parentPermissionId":2232,
       "permissionId":3809,
       "permissionToChild":3809
    },
    { 
       "itemName":"m.systemSettings",
       "parentPermissionId":3809,
       "permissionId":663,
       "permissionToChild":3033
    },
    { 
       "itemName":"m.Orchestration",
       "parentPermissionId":3809,
       "permissionId":673,
       "permissionToChild":323
    },
    { 
       "itemName":"m.appManager",
       "parentPermissionId":3809,
       "permissionId":683,
       "permissionToChild":324
    },
    { 
       "itemName":"m.dataManagement",
       "parentPermissionId":3809,
       "permissionId":693,
       "permissionToChild":325
    },
    { 
       "itemName":"m.systemMonitoring",
       "parentPermissionId":3809,
       "permissionId":713,
       "permissionToChild":326
    },
    { 
       "itemName":"m.bigDataSciencePlatform",
       "parentPermissionId":3809,
       "permissionId":723,
       "permissionToChild":327
    },
    { 
       "itemName":"m.policyEnforcement",
       "parentPermissionId":3809,
       "permissionId":733,
       "permissionToChild":328
    },
    { 
       "itemName":"m.questionnaireBuilder",
       "parentPermissionId":3809,
       "permissionId":743,
       "permissionToChild":329
    },
    { 
       "itemName":"m.dataCuration",
       "parentPermissionId":3809,
       "permissionId":753,
       "permissionToChild":330
    },
    { 
       "itemName":"m.decisioncoring",
       "parentPermissionId":3809,
       "permissionId":763,
       "permissionToChild":331
    },
    { 
       "itemName":"m.documentParsing",
       "parentPermissionId":3809,
       "permissionId":773,
       "permissionToChild":332
    },
    { 
       "itemName":"m.sourceManagement",
       "parentPermissionId":3809,
       "permissionId":783,
       "permissionToChild":1874
    },
    { 
       "itemName":"m.userManagement",
       "parentPermissionId":3809,
       "permissionId":793,
       "permissionToChild":333
    },
    { 
       "itemName":"d.creditCards",
       "parentPermissionId":null,
       "permissionId":2222,
       "permissionToChild":2222
    },
    { 
       "itemName":"g.enrich",
       "parentPermissionId":2222,
       "permissionId":2662,
       "permissionToChild":2662
    },
    { 
       "itemName":"m.advancedSearch",
       "parentPermissionId":2662,
       "permissionId":2004,
       "permissionToChild":2000
    },
    { 
       "itemName":"m.onboarding",
       "parentPermissionId":2662,
       "permissionId":105,
       "permissionToChild":2912
    },
    { 
       "itemName":"g.discover",
       "parentPermissionId":2222,
       "permissionId":2007,
       "permissionToChild":2007
    },
    { 
       "itemName":"m.dashboard",
       "parentPermissionId":2007,
       "permissionId":115,
       "permissionToChild":3220
    },
    { 
       "itemName":"m.workspace",
       "parentPermissionId":2007,
       "permissionId":124,
       "permissionToChild":2913
    },
    { 
       "itemName":"m.investigationConsole",
       "parentPermissionId":2007,
       "permissionId":134,
       "permissionToChild":2914
    },
    { 
       "itemName":"m.transactionMonitoring",
       "parentPermissionId":2007,
       "permissionId":144,
       "permissionToChild":309
    },
    { 
       "itemName":"m.marketIntelligence",
       "parentPermissionId":2007,
       "permissionId":154,
       "permissionToChild":310
    },
    { 
       "itemName":"m.adverseTransactions",
       "parentPermissionId":2007,
       "permissionId":164,
       "permissionToChild":311
    },
    { 
       "itemName":"m.fraud",
       "parentPermissionId":2007,
       "permissionId":174,
       "permissionToChild":312
    },
    { 
       "itemName":"m.transactionIntelligence",
       "parentPermissionId":2007,
       "permissionId":184,
       "permissionToChild":313
    },
    { 
       "itemName":"m.eDiscovery",
       "parentPermissionId":2007,
       "permissionId":194,
       "permissionToChild":314
    },
    { 
       "itemName":"m.alertManagement",
       "parentPermissionId":2007,
       "permissionId":147,
       "permissionToChild":2486
    },
    { 
       "itemName":"g.predict",
       "parentPermissionId":2222,
       "permissionId":2030,
       "permissionToChild":2030
    },
    { 
       "itemName":"Personalization",
       "parentPermissionId":2030,
       "permissionId":604,
       "permissionToChild":317
    },
    { 
       "itemName":"g.act",
       "parentPermissionId":2222,
       "permissionId":3090,
       "permissionToChild":3090
    },
    { 
       "itemName":"m.entity",
       "parentPermissionId":3090,
       "permissionId":614,
       "permissionToChild":318
    },
    { 
       "itemName":"m.cases",
       "parentPermissionId":3090,
       "permissionId":624,
       "permissionToChild":319
    },
    { 
       "itemName":"m.linkAnalysis",
       "parentPermissionId":3090,
       "permissionId":634,
       "permissionToChild":320
    },
    { 
       "itemName":"m.Underwriting",
       "parentPermissionId":3090,
       "permissionId":644,
       "permissionToChild":321
    },
    { 
       "itemName":"m.auditTrail",
       "parentPermissionId":3090,
       "permissionId":654,
       "permissionToChild":322
    },
    { 
       "itemName":"g.manage",
       "parentPermissionId":2222,
       "permissionId":3803,
       "permissionToChild":3803
    },
    { 
       "itemName":"m.systemSettings",
       "parentPermissionId":3803,
       "permissionId":664,
       "permissionToChild":3033
    },
    { 
       "itemName":"m.Orchestration",
       "parentPermissionId":3803,
       "permissionId":674,
       "permissionToChild":323
    },
    { 
       "itemName":"m.appManager",
       "parentPermissionId":3803,
       "permissionId":684,
       "permissionToChild":324
    },
    { 
       "itemName":"m.dataManagement",
       "parentPermissionId":3803,
       "permissionId":694,
       "permissionToChild":325
    },
    { 
       "itemName":"m.systemMonitoring",
       "parentPermissionId":3803,
       "permissionId":714,
       "permissionToChild":326
    },
    { 
       "itemName":"m.bigDataSciencePlatform",
       "parentPermissionId":3803,
       "permissionId":724,
       "permissionToChild":327
    },
    { 
       "itemName":"m.policyEnforcement",
       "parentPermissionId":3803,
       "permissionId":734,
       "permissionToChild":328
    },
    { 
       "itemName":"m.questionnaireBuilder",
       "parentPermissionId":3803,
       "permissionId":744,
       "permissionToChild":329
    },
    { 
       "itemName":"m.dataCuration",
       "parentPermissionId":3803,
       "permissionId":754,
       "permissionToChild":330
    },
    { 
       "itemName":"m.decisioncoring",
       "parentPermissionId":3803,
       "permissionId":764,
       "permissionToChild":331
    },
    { 
       "itemName":"m.documentParsing",
       "parentPermissionId":3803,
       "permissionId":774,
       "permissionToChild":332
    },
    { 
       "itemName":"m.sourceManagement",
       "parentPermissionId":3803,
       "permissionId":784,
       "permissionToChild":1874
    },
    { 
       "itemName":"m.userManagement",
       "parentPermissionId":3803,
       "permissionId":794,
       "permissionToChild":333
    },
    { 
       "itemName":"d.socialListening",
       "parentPermissionId":null,
       "permissionId":2332,
       "permissionToChild":2332
    },
    { 
       "itemName":"g.enrich",
       "parentPermissionId":2332,
       "permissionId":2675,
       "permissionToChild":2675
    },
    { 
       "itemName":"m.advancedSearch",
       "parentPermissionId":2675,
       "permissionId":2005,
       "permissionToChild":2000
    },
    { 
       "itemName":"m.onboarding",
       "parentPermissionId":2675,
       "permissionId":106,
       "permissionToChild":2912
    },
    { 
       "itemName":"g.discover",
       "parentPermissionId":2332,
       "permissionId":2907,
       "permissionToChild":2907
    },
    { 
       "itemName":"m.dashboard",
       "parentPermissionId":2907,
       "permissionId":116,
       "permissionToChild":3220
    },
    { 
       "itemName":"m.workspace",
       "parentPermissionId":2907,
       "permissionId":125,
       "permissionToChild":2913
    },
    { 
       "itemName":"m.investigationConsole",
       "parentPermissionId":2907,
       "permissionId":135,
       "permissionToChild":2914
    },
    { 
       "itemName":"m.transactionMonitoring",
       "parentPermissionId":2907,
       "permissionId":145,
       "permissionToChild":309
    },
    { 
       "itemName":"m.marketIntelligence",
       "parentPermissionId":2907,
       "permissionId":155,
       "permissionToChild":310
    },
    { 
       "itemName":"m.adverseTransactions",
       "parentPermissionId":2907,
       "permissionId":165,
       "permissionToChild":311
    },
    { 
       "itemName":"m.fraud",
       "parentPermissionId":2907,
       "permissionId":175,
       "permissionToChild":312
    },
    { 
       "itemName":"m.transactionIntelligence",
       "parentPermissionId":2907,
       "permissionId":185,
       "permissionToChild":313
    },
    { 
       "itemName":"m.eDiscovery",
       "parentPermissionId":2907,
       "permissionId":195,
       "permissionToChild":314
    },
    { 
       "itemName":"m.alertManagement",
       "parentPermissionId":2907,
       "permissionId":157,
       "permissionToChild":2486
    },
    { 
       "itemName":"g.predict",
       "parentPermissionId":2332,
       "permissionId":2730,
       "permissionToChild":2730
    },
    { 
       "itemName":"Personalization",
       "parentPermissionId":2730,
       "permissionId":605,
       "permissionToChild":317
    },
    { 
       "itemName":"g.act",
       "parentPermissionId":2332,
       "permissionId":3190,
       "permissionToChild":3190
    },
    { 
       "itemName":"m.entity",
       "parentPermissionId":3190,
       "permissionId":615,
       "permissionToChild":318
    },
    { 
       "itemName":"m.cases",
       "parentPermissionId":3190,
       "permissionId":625,
       "permissionToChild":319
    },
    { 
       "itemName":"m.linkAnalysis",
       "parentPermissionId":3190,
       "permissionId":635,
       "permissionToChild":320
    },
    { 
       "itemName":"m.Underwriting",
       "parentPermissionId":3190,
       "permissionId":645,
       "permissionToChild":321
    },
    { 
       "itemName":"m.auditTrail",
       "parentPermissionId":3190,
       "permissionId":655,
       "permissionToChild":322
    },
    { 
       "itemName":"g.manage",
       "parentPermissionId":2332,
       "permissionId":3888,
       "permissionToChild":3888
    },
    { 
       "itemName":"m.systemSettings",
       "parentPermissionId":3888,
       "permissionId":665,
       "permissionToChild":3033
    },
    { 
       "itemName":"m.Orchestration",
       "parentPermissionId":3888,
       "permissionId":675,
       "permissionToChild":323
    },
    { 
       "itemName":"m.appManager",
       "parentPermissionId":3888,
       "permissionId":685,
       "permissionToChild":324
    },
    { 
       "itemName":"m.dataManagement",
       "parentPermissionId":3888,
       "permissionId":695,
       "permissionToChild":325
    },
    { 
       "itemName":"m.systemMonitoring",
       "parentPermissionId":3888,
       "permissionId":715,
       "permissionToChild":326
    },
    { 
       "itemName":"m.bigDataSciencePlatform",
       "parentPermissionId":3888,
       "permissionId":725,
       "permissionToChild":327
    },
    { 
       "itemName":"m.policyEnforcement",
       "parentPermissionId":3888,
       "permissionId":735,
       "permissionToChild":328
    },
    { 
       "itemName":"m.questionnaireBuilder",
       "parentPermissionId":3888,
       "permissionId":745,
       "permissionToChild":329
    },
    { 
       "itemName":"m.dataCuration",
       "parentPermissionId":3888,
       "permissionId":755,
       "permissionToChild":330
    },
    { 
       "itemName":"m.decisioncoring",
       "parentPermissionId":3888,
       "permissionId":765,
       "permissionToChild":331
    },
    { 
       "itemName":"m.documentParsing",
       "parentPermissionId":3888,
       "permissionId":775,
       "permissionToChild":332
    },
    { 
       "itemName":"m.sourceManagement",
       "parentPermissionId":3888,
       "permissionId":785,
       "permissionToChild":1874
    },
    { 
       "itemName":"m.userManagement",
       "parentPermissionId":3888,
       "permissionId":795,
       "permissionToChild":333
    },
    { 
       "itemName":"d.insurance",
       "parentPermissionId":null,
       "permissionId":2095,
       "permissionToChild":2095
    },
    { 
       "itemName":"g.enrich",
       "parentPermissionId":2095,
       "permissionId":2990,
       "permissionToChild":2990
    },
    { 
       "itemName":"m.advancedSearch",
       "parentPermissionId":2990,
       "permissionId":2006,
       "permissionToChild":2000
    },
    { 
       "itemName":"m.onboarding",
       "parentPermissionId":2990,
       "permissionId":107,
       "permissionToChild":2912
    },
    { 
       "itemName":"g.discover",
       "parentPermissionId":2095,
       "permissionId":2887,
       "permissionToChild":2887
    },
    { 
       "itemName":"m.dashboard",
       "parentPermissionId":2887,
       "permissionId":117,
       "permissionToChild":3220
    },
    { 
       "itemName":"m.workspace",
       "parentPermissionId":2887,
       "permissionId":126,
       "permissionToChild":2913
    },
    { 
       "itemName":"m.investigationConsole",
       "parentPermissionId":2887,
       "permissionId":136,
       "permissionToChild":2914
    },
    { 
       "itemName":"m.transactionMonitoring",
       "parentPermissionId":2887,
       "permissionId":146,
       "permissionToChild":309
    },
    { 
       "itemName":"m.marketIntelligence",
       "parentPermissionId":2887,
       "permissionId":156,
       "permissionToChild":310
    },
    { 
       "itemName":"m.adverseTransactions",
       "parentPermissionId":2887,
       "permissionId":166,
       "permissionToChild":311
    },
    { 
       "itemName":"m.fraud",
       "parentPermissionId":2887,
       "permissionId":176,
       "permissionToChild":312
    },
    { 
       "itemName":"m.transactionIntelligence",
       "parentPermissionId":2887,
       "permissionId":186,
       "permissionToChild":313
    },
    { 
       "itemName":"m.eDiscovery",
       "parentPermissionId":2887,
       "permissionId":196,
       "permissionToChild":314
    },
    { 
       "itemName":"m.alertManagement",
       "parentPermissionId":2887,
       "permissionId":167,
       "permissionToChild":2486
    },
    { 
       "itemName":"g.predict",
       "parentPermissionId":2095,
       "permissionId":2444,
       "permissionToChild":2444
    },
    { 
       "itemName":"Personalization",
       "parentPermissionId":2444,
       "permissionId":606,
       "permissionToChild":317
    },
    { 
       "itemName":"g.act",
       "parentPermissionId":2095,
       "permissionId":3920,
       "permissionToChild":3920
    },
    { 
       "itemName":"m.entity",
       "parentPermissionId":3920,
       "permissionId":616,
       "permissionToChild":318
    },
    { 
       "itemName":"m.cases",
       "parentPermissionId":3920,
       "permissionId":626,
       "permissionToChild":319
    },
    { 
       "itemName":"m.linkAnalysis",
       "parentPermissionId":3920,
       "permissionId":636,
       "permissionToChild":320
    },
    { 
       "itemName":"m.Underwriting",
       "parentPermissionId":3920,
       "permissionId":646,
       "permissionToChild":321
    },
    { 
       "itemName":"m.auditTrail",
       "parentPermissionId":3920,
       "permissionId":656,
       "permissionToChild":322
    },
    { 
       "itemName":"g.manage",
       "parentPermissionId":2095,
       "permissionId":3088,
       "permissionToChild":3088
    },
    { 
       "itemName":"m.systemSettings",
       "parentPermissionId":3088,
       "permissionId":666,
       "permissionToChild":3033
    },
    { 
       "itemName":"m.Orchestration",
       "parentPermissionId":3088,
       "permissionId":676,
       "permissionToChild":323
    },
    { 
       "itemName":"m.appManager",
       "parentPermissionId":3088,
       "permissionId":686,
       "permissionToChild":324
    },
    { 
       "itemName":"m.dataManagement",
       "parentPermissionId":3088,
       "permissionId":696,
       "permissionToChild":325
    },
    { 
       "itemName":"m.systemMonitoring",
       "parentPermissionId":3088,
       "permissionId":716,
       "permissionToChild":326
    },
    { 
       "itemName":"m.bigDataSciencePlatform",
       "parentPermissionId":3088,
       "permissionId":726,
       "permissionToChild":327
    },
    { 
       "itemName":"m.policyEnforcement",
       "parentPermissionId":3088,
       "permissionId":736,
       "permissionToChild":328
    },
    { 
       "itemName":"m.questionnaireBuilder",
       "parentPermissionId":3088,
       "permissionId":746,
       "permissionToChild":329
    },
    { 
       "itemName":"m.dataCuration",
       "parentPermissionId":3088,
       "permissionId":756,
       "permissionToChild":330
    },
    { 
       "itemName":"m.decisioncoring",
       "parentPermissionId":3088,
       "permissionId":766,
       "permissionToChild":331
    },
    { 
       "itemName":"m.documentParsing",
       "parentPermissionId":3088,
       "permissionId":776,
       "permissionToChild":332
    },
    { 
       "itemName":"m.sourceManagement",
       "parentPermissionId":3088,
       "permissionId":786,
       "permissionToChild":1874
    },
    { 
       "itemName":"m.userManagement",
       "parentPermissionId":3088,
       "permissionId":796,
       "permissionToChild":333
    },


    {"itemName": "alertsList","parentPermissionId": 2486,"permissionId": 2978 },
    {"itemName": "exportData","parentPermissionId": 2978,"permissionId" : 4092 },
    {"itemName": "groupLevel","parentPermissionId": 2978,"permissionId": 4093 },
    {"itemName": "assignee","parentPermissionId": 2978,"permissionId": 4094 },
    {"itemName": "status","parentPermissionId": 2978,"permissionId": 4095 },
    {"itemName": "commentBox","parentPermissionId": 2978,"permissionId": 4096 },
    {"itemName": "quickInfo","parentPermissionId": 2978,"permissionId": 4097 },
    {"itemName": "Auditing","parentPermissionId": 2978,"permissionId": 4098 },


    {"itemName": "feedList","parentPermissionId": 2486,"permissionId": 1552},
    {"itemName": "exportData","parentPermissionId": 1552,"permissionId": 4099 },
    {"itemName": "groupLevel","parentPermissionId": 1552,"permissionId": 4100 },
    {"itemName": "assignee","parentPermissionId": 1552,"permissionId": 4101 },
    {"itemName": "source","parentPermissionId": 1552,"permissionId": 4102 },
    {"itemName": "color","parentPermissionId": 1552,"permissionId": 4103 },
    {"itemName": "edit","parentPermissionId": 1552,"permissionId": 4104 },
    {"itemName": "history","parentPermissionId": 1552,"permissionId": 4105 },


    
    {"itemName": "alertsList","parentPermissionId": 117,"permissionId": 4000 },
    {"itemName": "exportData","parentPermissionId": 4000,"permissionId": 4001 },
    {"itemName": "groupLevel","parentPermissionId": 4000,"permissionId": 4002 },
    {"itemName": "assignee","parentPermissionId": 4000,"permissionId": 4003 },
    {"itemName": "status","parentPermissionId": 4000,"permissionId": 4004 },
    {"itemName": "commentBox","parentPermissionId": 4000,"permissionId": 4005 },
    {"itemName": "quickInfo","parentPermissionId": 4000,"permissionId": 4006 },
    {"itemName": "Auditing","parentPermissionId": 4000,"permissionId": 4007 },


    {"itemName": "feedList","parentPermissionId": 117,"permissionId": 4008},
    {"itemName": "exportData","parentPermissionId": 4008,"permissionId": 4009 },
    {"itemName": "groupLevel","parentPermissionId": 4008,"permissionId": 4010 },
    {"itemName": "assignee","parentPermissionId": 4008,"permissionId": 4011 },
    {"itemName": "source","parentPermissionId": 4008,"permissionId": 4012 },
    {"itemName": "color","parentPermissionId": 4008,"permissionId": 4013 },
    {"itemName": "edit","parentPermissionId": 4008,"permissionId": 4014 },
    {"itemName": "history","parentPermissionId": 4008,"permissionId": 4015 },


    
    {"itemName": "alertsList","parentPermissionId": 127,"permissionId": 4016 },
    {"itemName": "exportData","parentPermissionId": 4016,"permissionId": 4017 },
    {"itemName": "groupLevel","parentPermissionId": 4016,"permissionId": 4018 },
    {"itemName": "assignee","parentPermissionId": 4016,"permissionId": 4019 },
    {"itemName": "status","parentPermissionId": 4016,"permissionId": 4020 },
    {"itemName": "commentBox","parentPermissionId": 4016,"permissionId": 4021 },
    {"itemName": "quickInfo","parentPermissionId": 4016,"permissionId": 4022 },
    {"itemName": "Auditing","parentPermissionId": 4016,"permissionId": 4023 },


    {"itemName": "feedList","parentPermissionId": 127,"permissionId": 4024},
    {"itemName": "exportData","parentPermissionId": 4024,"permissionId": 4025 },
    {"itemName": "groupLevel","parentPermissionId": 4024,"permissionId": 4026 },
    {"itemName": "assignee","parentPermissionId": 4024,"permissionId": 4027 },
    {"itemName": "source","parentPermissionId": 4024,"permissionId": 4028 },
    {"itemName": "color","parentPermissionId": 4024,"permissionId": 4029 },
    {"itemName": "edit","parentPermissionId": 4024,"permissionId": 4030 },
    {"itemName": "history","parentPermissionId": 4024,"permissionId": 4031 },


    
    {"itemName": "alertsList","parentPermissionId": 137,"permissionId": 4032 },
    {"itemName": "exportData","parentPermissionId": 4032,"permissionId": 4033 },
    {"itemName": "groupLevel","parentPermissionId": 4032,"permissionId": 4034 },
    {"itemName": "assignee","parentPermissionId": 4032,"permissionId": 4035 },
    {"itemName": "status","parentPermissionId": 4032,"permissionId": 4036 },
    {"itemName": "commentBox","parentPermissionId": 4032,"permissionId": 4037 },
    {"itemName": "quickInfo","parentPermissionId": 4032,"permissionId": 4038 },
    {"itemName": "Auditing","parentPermissionId": 4032,"permissionId": 4039 },


    {"itemName": "feedList","parentPermissionId": 137,"permissionId": 4040},
    {"itemName": "exportData","parentPermissionId": 4040,"permissionId": 4041 },
    {"itemName": "groupLevel","parentPermissionId": 4040,"permissionId": 4042 },
    {"itemName": "assignee","parentPermissionId": 4040,"permissionId": 4043 },
    {"itemName": "source","parentPermissionId": 4040,"permissionId": 4044 },
    {"itemName": "color","parentPermissionId": 4040,"permissionId": 4045 },
    {"itemName": "edit","parentPermissionId": 4040,"permissionId": 4046 },
    {"itemName": "history","parentPermissionId": 4040,"permissionId": 4047 },


    
    {"itemName": "alertsList","parentPermissionId": 147,"permissionId": 4048 },
    {"itemName": "exportData","parentPermissionId": 4048,"permissionId": 4049 },
    {"itemName": "groupLevel","parentPermissionId": 4048,"permissionId": 4050 },
    {"itemName": "assignee","parentPermissionId": 4048,"permissionId": 4051 },
    {"itemName": "status","parentPermissionId": 4048,"permissionId": 4052 },
    {"itemName": "commentBox","parentPermissionId": 4048,"permissionId": 4053 },
    {"itemName": "quickInfo","parentPermissionId": 4048,"permissionId": 4054 },
    {"itemName": "Auditing","parentPermissionId": 4048,"permissionId": 4055 },


    {"itemName": "feedList","parentPermissionId": 147,"permissionId": 4056 },
    {"itemName": "exportData","parentPermissionId": 4056,"permissionId": 4057 },
    {"itemName": "groupLevel","parentPermissionId": 4056,"permissionId": 4058 },
    {"itemName": "assignee","parentPermissionId": 4056,"permissionId": 4059 },
    {"itemName": "source","parentPermissionId": 4056,"permissionId": 4060 },
    {"itemName": "color","parentPermissionId": 4056,"permissionId": 4061 },
    {"itemName": "edit","parentPermissionId": 4056,"permissionId": 4062 },
    {"itemName": "history","parentPermissionId": 4056,"permissionId": 4063 },


    
    {"itemName": "alertsList","parentPermissionId": 157,"permissionId": 4064 },
    {"itemName": "exportData","parentPermissionId": 4064,"permissionId": 4065 },
    {"itemName": "groupLevel","parentPermissionId": 4064,"permissionId": 4066 },
    {"itemName": "assignee","parentPermissionId": 4064,"permissionId": 4067 },
    {"itemName": "status","parentPermissionId": 4064,"permissionId": 4068 },
    {"itemName": "commentBox","parentPermissionId": 4064,"permissionId": 4069 },
    {"itemName": "quickInfo","parentPermissionId": 4064,"permissionId": 4070 },
    {"itemName": "Auditing","parentPermissionId": 4064,"permissionId": 4071 },


    {"itemName": "feedList","parentPermissionId": 157,"permissionId": 4072},
    {"itemName": "exportData","parentPermissionId": 4072,"permissionId": 4073 },
    {"itemName": "groupLevel","parentPermissionId": 4072,"permissionId": 4074 },
    {"itemName": "assignee","parentPermissionId": 4072,"permissionId": 4075 },
    {"itemName": "source","parentPermissionId": 4072,"permissionId": 4076 },
    {"itemName": "color","parentPermissionId": 4072,"permissionId": 4077 },
    {"itemName": "edit","parentPermissionId": 4072,"permissionId": 4078 },
    {"itemName": "history","parentPermissionId": 4072,"permissionId": 4079 },


    
    {"itemName": "alertsList","parentPermissionId": 167,"permissionId": 4080 },
    {"itemName": "exportData","parentPermissionId": 4080,"permissionId": 4081 },
    {"itemName": "groupLevel","parentPermissionId": 4080,"permissionId": 4082 },
    {"itemName": "assignee","parentPermissionId": 4080,"permissionId": 4083 },
    {"itemName": "status","parentPermissionId": 4080,"permissionId": 4084 },
    {"itemName": "commentBox","parentPermissionId": 4080,"permissionId": 4085 },
    {"itemName": "quickInfo","parentPermissionId": 4080,"permissionId": 4086 },
    {"itemName": "Auditing","parentPermissionId": 4080,"permissionId": 4087 },


    {"itemName": "feedList","parentPermissionId": 167,"permissionId": 4088},
    {"itemName": "exportData","parentPermissionId": 4088,"permissionId": 4089 },
    {"itemName": "groupLevel","parentPermissionId": 4088,"permissionId": 4090 },
    {"itemName": "assignee","parentPermissionId": 4088,"permissionId": 4091 },
    {"itemName": "source","parentPermissionId": 4088,"permissionId": 4092 },
    {"itemName": "color","parentPermissionId": 4088,"permissionId": 4093 },
    {"itemName": "edit","parentPermissionId": 4088,"permissionId": 4094 },
    {"itemName": "history","parentPermissionId": 4088,"permissionId": 4095 },



     
    
    
 ]
